### ISSUE TITLE
stop command

### ISSUE THREAD

**Issue by mayank8920** [justwolfii/DiscordPinger#4]
bro stop command is not working

**Comment by IdkWhosThis** [comment]
You have to tell me more info about what happened.. is tehre any error?

**Comment by mayank8920** [comment]
> You have to tell me more info about what happened.. is tehre any error?

Bro I use command ping than ping is started but when I use stop command so I got reply stopping ping then new msg stopped pinging but it won't stop so ping command is working but stop won't work

**Comment by mayank8920** [comment]
Bro I use command ping than ping is started but when I use stop command so I got reply stopping ping then new msg stopped pinging but it won't stop so ping command is working but stop won't work

**Comment by IdkWhosThis** [comment]
Iam on my way from school. I will look at it and if needed, I will update the code.

**Comment by mayank8920** [comment]
Ok

**Comment by lapcatlak** [comment]
and what

**Comment by IdkWhosThis** [comment]
I decided to end this project. It will be archived and completly remade on my main github account. Link will be posted into readme & into this issue.

**Comment by p0ndobear** [comment]
Where is the link to the new one?

**Comment by IdkWhosThis** [comment]
The bot will be done next week. I had alot of work last few months. Once it'll be done, link will be published.
